### PR TITLE
more bug fixes, mainly gui button fixes, button placement tweaks

### PR DESCRIPTION
**Pull request by PseudonymPatel**
Small changes, but a lot of bug fixes relating to the crafting system. Made GUI buttons adapt to TiM and TC tables.
Made some tweaks to button placement and size and they look better now. 
Fixed bug that was reported.

Forgot to write comment but lines 89-90 in TileEntityStorage is so the trains will not take up the two button slots (it fills vertical columns first before going to next column, previously filled rows before going to next row)

Issue that I cannot fix with packet system or something - pressing either button crashes the game.

### CODE REVIEW

**Comment by Tsoccerguy3** [comment]
Compiles ok , but crashes on start up as a standalone mod
[latest.log](https://github.com/EternalBlueFlame/Traincraft-5/files/5791622/latest.log)

**Comment by EternalBlueFlame** [comment]
looks like there's some scala imports, i'll have to deal with those in the next push

**Comment by dusieq95** [comment]
i fixed this problem replacing `import scala.actors.threadpool.Arrays;` with `import java.util.Arrays;` i'm not programist or something i just found the similar problem on EnderIOAddons.

**Comment by EternalBlueFlame** [comment]
Yeah, it's a pretty simple fix.
My guess is that i hit the wrong thing when doing ALT-Enter to import.
gonna cover a few things first and i'll have the fix in the next push.

**Comment by EternalBlueFlame** [comment]
Alright, this should be fixed as of https://github.com/EternalBlueFlame/Traincraft-5/commit/5ef3aeaec3c5cb58e8be74baeeec0b6ce5e30b59

**Pull request merged**
