### PR TITLE
Fix weird rotating and derails on slopes

### PR DESCRIPTION
**Pull request by tpeterka1**
This one line removal fixes derailments when going up slopes (these https://streamable.com/t3gy8h)

I tested it and it works fine now https://streamable.com/vvo6pf

### CODE REVIEW

**Comment by EternalBlueFlame** [comment]
omitting the super call breaks the bogie's interaction with some railcraft functionality.

**Comment by tpeterka1** [comment]
I guess there must be an error in that then? Because it doesn't flip without the call.

**Comment by EternalBlueFlame** [comment]
Possibly but unlikely.
If anything it's probably something like gravity logic or some garbage like that.

The thing is that railcraft functionality is injected into the host class (entity minecart) from railcraft, So if we don't call the super method then we can't use the features.

TheDoctor looked into this more, and from his testing moving the update call to **after** we've checked whether it's an extension of a vanilla/railcraft rail or not, seems to fix the problem in addition to keeping railcraft functionality.

So that will likely be how it gets done for the next release.

**Comment by tpeterka1** [comment]
Alright then, thanks for clearing these things up for me

**Pull request closed without merging**
