### PR TITLE
IC4-Stock texture improvements and HUD name changes(en_US and da_DK)

### PR DESCRIPTION
**Pull request by cool9535**
You can decide if you want to keep the train og not, that is fine for me

### CODE REVIEW

**Comment by cool9535** [comment]
IC4 Texture Improvements:






Texture Demo pack:
[Traincraft Texture demos.zip](https://github.com/EternalBlueFlame/Traincraft-5/files/5565965/Traincraft.Texture.demos.zip)

**Comment by EternalBlueFlame** [comment]
there's a large degree of changes in here that aren't related to the IC4, and it has a lot of related conflicts.

**Comment by cool9535** [comment]
Alright, yesterday i Re-Forked TC completely, I can easily  re-add only the IC4 related stuff in a new pull request, is that good with you?

**Comment by EternalBlueFlame** [comment]
yeah that works fine.

**Comment by cool9535** [comment]
Allright, I'll do that

**Pull request closed without merging**
