### PR TITLE
Added language files and fixed item names.

### PR DESCRIPTION
**Pull request by WaDelma**
And fixed NullPointerException caused by ItemBlockFluid.

### CODE REVIEW

**Comment by canitzp** [comment]
GameRegistry.registerItem needs the modid, otherwise it can create problems with other mods that have items with the same name.

**Comment by WaDelma** [comment]
Well that breaks the names and the broken names already have the mod id

**Comment by Pdevo** [comment]
Hi there, I have made IT translations for traincraft, can I push them?

**Comment by canitzp** [comment]
I meant item.setUnlocalizedName() instead of GameRegistry.register. Sorry for this.

**Comment by WaDelma** [comment]
Well that forge API is strange... It adds the prefix but doesn't seem to put prefixed name anywhere available.

Anyways... All language files has to be updated if we add the prefix... Will do that now

**Comment by WaDelma** [comment]
Anyways... All language files has to be updated if we add the prefix... Will do that now

**Comment by WaDelma** [comment]
Should be fixed now

**Pull request merged**
