### PR TITLE
1.7 community 4.3

### PR DESCRIPTION
**Pull request by zetti68**
Hello developers of Traincraft,
I spent a little time to change four topics in Traincraft-6:
1. build.gradle, .gitignore
I use Eclipse and changed something to get a working project with Eclipse and EGradle

2. Locomotive.java: compilation bug, Loader was not in imports

3. RecipeHander.java:
- I added "sheetPlastic" and "platePlastic" (OreDictionary) to plastics to support GregTech6
- If any kind of plastic without "dustPlastic" is available, "dustPlastic" is not necessary in recipes in my mind. If none of them is available, use "dustPlastic" in recipes.

4. NEIAssemblyTableRecipePlugin, NEITraincraftWorkbenchRecipePlugin:
I hope, I found a working solution that handles recipes in NEI correctly.
My fixes in detail:
- show correct tier of results in assembly workbench
- show recipes with correct cycling of materials found in ore dictionary
- show correct count of recipes in usage mode

Please note, I only changed 1.7-community-4.3. I'm a little bit confused to find three different 1.7-branches. I hope, community branch was the right one to change.

Best regards
Zetti68

### CODE REVIEW

**Comment by EternalBlueFlame** [comment]
This push will need some significant modifications before we can merge it.

This removes license files, both from file and through the gitIgnore, which is against the terms of service for multiple apis.

It adds a large number of unauthorized apis to the build Gradle, which scale from potentially questionable on usage rights, to invalid and could potentially cause issues in some workspaces.

It removes the necessary grade tech repositories from the build Gradle.
The run directory is changed to eclipse which will cause a problem with eclipse runtime environments.

Likely the reason that you couldn't set it up correctly in eclipse was because you weren't using the Gradle import plugin. The previous setup worked just fine for eclipse.

The check for dust plastic should be an addition to the current check for plastic, rather than a replacement for if it's null, since there could be scenarios where both are true.

The changes to the crafting system define some significant structure changes to how the arrays and loops work, and I'll need to test those to be sure they work as intended.

Despite the issues, I am genuinely thrilled to see people working on this.

**Review by zetti68 — COMMENTED** [review]
Thanks, your issues are ok.
.gitignore: I generated a project in eclipse with forge-1.7.10-10.13.4.1614-1.7.10-src.zip and copied your files into it. SourceTree marked some files as new and so I added these to .gitignore instead adding to repository. Sorry
gradle.build: I used an old version of forge-1.7.10...zip with an old version of gradle.build in it. The repository sonatype was in this version. But Sonatype and block processResources are not used, deletion of both is ok.
I added repository files.minecraftforge.net/maven only.

Usage of dustPlastic in recipes: it is also possible to use Traincraft.cfg to add it to recipes or not (e.g. key B:USE_DUSTPLASTIC_IN_RECIPES=true)
Please let me know I can change it.

Additionally short information to NEITraincraftWorkbenchRecipePlugin: the original version handles ShapelessTrainRecipes too. My version supports ShapedTrainRecipes only.
Here are my reasons to break handling of ShapeLessTrainRecipes:
- Class ShapelessTrainRecipes is not referenced, no shapeless recipe was added in Traincraft
- The type of member variable recipeListWB is List\<ShapedTrainRecipes\> -> potential ClassCastException 

I'm so sorry, but a found a bug in cycling today:
The methods getCycledIngredients in NEIxxxPlugins change the items in each slot without any reference to other slots. But this is wrong.
Example: recipe of transformer needs 5 steel ingots. I found two different steel ingots in my test version of minecraft/forge: GT and Railcraft.
The last version of NEITraincraftWorkbenchRecipePlugin shows combination of GT and Railcraft steel ingot in NEI at same time. But this is wrong, a recipe with mixed types of ore dictionary "ingotSteel" is not defined.
The right solution is to show identical steel ingot in all five slots. That means, that NEI shows all slots of one defined recipe and cycles through all recipes, they are defined for same output. 
In the example "transformer" NEI shows only GT steel ingots in all 5 slots or Railcraft ingots. The items in second row are equal in both recipes.

I corrected it in my source code already and pushed it, please review my last changes too.

**Comment by zetti68** [comment]
I changed something once more:

NEITraincraft...Plugin and NEIAssembly...Plugin:
optimized: do not change item in ingredients, set ingredients to next recipe instead and show it
methods loadCraftingRecipes: given outputID do not match, special code was not necessary, deleted

I found not working recipes in Assembly table: 
- a combination of OreDictionary.WILDCARD_VALUE and a count of item > 1 do not work. If the damage is set to WILDCARD, the count of item will be only 1.
- multi value items (e.g. GT's plankWood) show only one kind of item in NEI
Solution:
- set ItemDamage to 0, if itemStack.getItemDamage() == OreDictionary.WILDCARD_VALUE
- use itemStack.getItemDamage(), if damage != wildcard.

I added item damage to coal and water bucket additionaly to prevent nonsense recipes like usage of "empty ingot"

**Comment by EternalBlueFlame** [comment]
looks good now, thanks for taking the extra effort.

**Comment by zetti68** [comment]
My best thanks. A wish you all the best.

**Pull request merged**
