### PR TITLE
Overspeed updates. I had this idea 2 minutes ago lol.

### PR DESCRIPTION
**Pull request by FloofyPeachy**
lol
This next verse, this next verse though
These bars
Watch this some sht, go
Poopy-di scoop
Scoop-diddy-whoop
Whoop-di-scoop-di-poop

### CODE REVIEW

**Comment by EternalBlueFlame** [comment]
That is the least constructive push description i have ever read in my life.
Including the ones that are null.

**Comment by FloofyPeachy** [comment]
Apoligies for this meme.
Basicly with MTC if you over speed then it will give you a warning, and if you don't do anything about it then it will slow you down.

**Comment by EternalBlueFlame** [comment]
That's cool, but why store it as a bool? Seems like something that could just be checked in realtime on the gui and during the update phase?
I mean an int to see how long it's been going so it wont just slow you immediately, sure, that makes sense.

**Comment by FloofyPeachy** [comment]
Hmm, alright. To the editing board!

**Pull request closed without merging**
