### PR TITLE
Update it_IT.lang

### PR DESCRIPTION
**Pull request by pietrodevo**

### CODE REVIEW

**Comment by EternalBlueFlame** [comment]
why was the majority of the language file removed?

**Comment by pietrodevo** [comment]
I noticed there were duplications, so took again the en_US from scratch and fixed these

**Comment by NitroxydeX** [comment]
duplicates? You removed the NEEDED Fluid section otherwise the tanks aren't displaying the right stuff. It was added by me on purpose.

**Comment by pietrodevo** [comment]
Then I messed up, sorry, I will immediately fix all.

Edit:
The fact the lang file was 900+ lines was because of repetitions (maybe some messing with cut/past or adding), the fluid section was left behind by my mistake, now I fixed the mess, sorry for the inconvenience

**Comment by EternalBlueFlame** [comment]
There weren't repetitions though, those were all valid language file entries because of how forge handles naming.

It seems like there's a lot repeated but look closely at the URI for each entry, the language file has to cover achievements, items, entities, tile entities, and blocks all separately.

I apologize this wasn't better explained. I'll make note to document this system better in the future.

**Pull request closed without merging**
