### PR TITLE
Improved Performance / reduced CPU-usage when checking for allowed items

### PR DESCRIPTION
**Pull request by TheBlueCrystal**
Hello,
I've modified the allowed-item-check for freight-cars a bit so that it's no longer necessary to loop over the complete log- / plank-list, but instead use a single hash map lookup.

### CODE REVIEW

**Comment by canitzp** [comment]
It would be better if you fork this repo and create a pr out of this instead out of the 1.7 main repo at Traincraft/Traincraft

**Comment by TheBlueCrystal** [comment]
Hello canitzp!
Thanks for the advice!
I am new to GitHub and am struggling a bit with it's forking logic at the moment.
I pressed the "fork"-button on the page of EthernalBlueFlame's repo, and thought it would fork his repo.
When I click on the fork-button again, it says that my repo is a fork of Traincraft/Traincraft ... what am I doing wrong?

**Comment by NitroxydeX** [comment]
@TheBlueCrystal If you press "Fork" on this repo it _SHOULD_ fork this repo. Tested it and it works. Make sure to delete other Repos with the SAME name on your account and redo the fork.

make sure to save your changes of all three pull requests somewhere. and you can do just one pull request for every change. If you want to make it look better push one commit per change

**Comment by NitroxydeX** [comment]
And make sure you sign this: https://cla-assistant.io/Mrbrutal/Traincraft
Otherwise we can't merge your pull requests

**Pull request closed without merging**
