### PR TITLE
nbt fixe

### PR DESCRIPTION
**Pull request by quentfr21**
hello

after some try i finaly fix it (i think )

maybe you need to make some more test (code pushed to a fork on my account)

but i mak modification @ texture caching push

if it's good that great 
thanks to take a look

### CODE REVIEW

**Comment by EternalBlueFlame** [comment]
this will just break NBT reading and writing for every rollingstock that has its own custom NBT on top of normal, plus it reverts the new changes i just uploaded.
It also changes the entity NBT calls to an improper NBT call.
//EDIT: actually it reverts changes from a few weeks, when was the last time you synced this...?

**Comment by quentfr21** [comment]
i make some try  on it and it looks like work like this 
 i think entity call is only needed one time after you use normal nbt (i think)

//EDIT: 
i make it this night with the cahing texture push

**Comment by EternalBlueFlame** [comment]
you're confusing read/writeEntityToNBT with read/writeSpawnData, double over the forge documentation for 1.7.
You also disable super calls for NBT on a number of rollingstock, I shouldn't even have to explain the problems that creates.

And again, it still rolls back all the changes to the source from the past few weeks because you didn't sync your local repo before pushing.

**Comment by quentfr21** [comment]
i just change read/writeEnitityTONBT to read/writeToNBT i don't touch the spawn data

after try i see the super call cause a class cast error  while Writing String to a Byte
that's why a remove it but it's writed and readed great

if it's not help sorry and thank to have take a look on it

**Comment by EternalBlueFlame** [comment]
I'll do some testing and doublecheck, but it's still not properly synced with the current repo which breaks a lot of the recent fixes and changes (for example the B-units and windmill), which is a problem. And in most classes you comment out the super call in the NBT read/write of the trains/rollingstock which is a big problem.

**Comment by quentfr21** [comment]
maybe i can remake this change with the lastest push

maybe download and build it from my account and make try save/read with some train

edit// yes i have to make more test with the commented out super in nbt
i will try to remake all with syncked fork without commented out nbt

thanks

**Comment by EternalBlueFlame** [comment]
just found it in the documentation, line 1659 of the entity class

> 
    /**
     * (abstract) Protected helper method to read subclass entity data from NBT.
     */
    protected abstract void readEntityFromNBT(NBTTagCompound p_70037_1_);

    /**
     * (abstract) Protected helper method to write subclass entity data to NBT.
     */
    protected abstract void writeEntityToNBT(NBTTagCompound p_70014_1_);

So perhaps the issue is the core classes are overriding it rather than implementing it. (of course their sub-classes have to override it and do a super call as they have been.)

I've also been doing some testing of your method in the rewrite, and it's very prone to crashing.

**Comment by quentfr21** [comment]
not good :)

**Pull request closed without merging**
