### PR TITLE
Create it_IT.lang

### PR DESCRIPTION
**Pull request by pietrodevo**
This is the italian locale made by me

### CODE REVIEW

**Comment by EternalBlueFlame** [comment]
Was this supposed to only be the language file?
If not could you tell me what exactly you wanted to add?

It seems that some commits that had to get reworked/moved around ended up included in your pull request.

**Comment by canitzp** [comment]
You language file wouldn't work, because at all things the modid "tc" is missing

**Comment by pietrodevo** [comment]
Sorry, my mistake, I just wanted to work the lang file

**Comment by pietrodevo** [comment]
I messed up with files, I'll correct everything

**Pull request closed without merging**
