### PR TITLE
Threads saves time when loading the game

### PR DESCRIPTION
**Pull request by jaredlll08**
I hope my formatting is fine, please just reformat it if it isn't.

Also since there isn't a CLA, I give you permission to use this code in any way you want.

### CODE REVIEW

**Review by Vazkii — APPROVED** [review]
haha thread go brrrrr

**Comment by EternalBlueFlame** [comment]
Traincraft is written specifically for java 6 and later.
This is java 8 and later code, and thus is incompatible.

**Comment by jaredlll08** [comment]
My mistake, give me a few minutes to fix it up :)

**Comment by jaredlll08** [comment]
I believe it is J6 now, I haven't used J6 in a few years, so just let me know what *isn't* J6 in it please

**Comment by EternalBlueFlame** [comment]
It is J6 now, however variable `evt` is being accessed from within an inner class, which is only a thing for final variables.

The easiest fix is going to be just moving the new thread thing inside of the check like this
`		if (specialUsers.size()==0 && evt.getSide().isClient()) {
		new Thread(new Runnable() {`

That seems to fix all issues.

Also since you're allowing permission to use this any way i deem fit, i'll be adding it to the rewrite as well. Although that's probably something you'd want anyway.

**Comment by jaredlll08** [comment]
errors are fixed

**Comment by EternalBlueFlame** [comment]
good work, I'm actually surprised you did it.
respect.

**Pull request merged**
